{% set name = "pygal" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygal-{{ version }}.tar.gz
  sha256: fbdee7351a7423e7907fb8a9c3b77305f6b5678cb2e6fd0db36a8825e42955ec

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - importlib_metadata
    - lxml

test:
  imports:
    - pygal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.pygal.org/
  summary: A Python svg graph plotting library
  license: LGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - Matt-BF
