{% set name = "pygal" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pygal-{{ version }}.tar.gz
  sha256: c0a0f34e5bc1c01975c2bfb8342ad521e293ad42e525699dd00c4d7a52c14b71

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - importlib_metadata
    - lxml

test:
  imports:
    - pygal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://www.pygal.org/
  summary: A Python svg graph plotting library
  license: LGPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - Matt-BF
